version: '3'
services:
  wordpress:
    container_name: wordpress-web
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./data/wp-content:/var/www/html/wp-content
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9091:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - network

  db:
    image: mysql:5.7.22
    container_name: wordpress-databse
    restart: always
    ports:
      - "3309"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - network

  phpmyadmin:
    container_name: wordpress-phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9192:80
    environment:
      PMA_HOST: db
    networks:
      - network

networks:
  network: